### ISSUE TITLE
Z-Stop Notes

### ISSUE THREAD

**Issue by maximus5684** [embracemaking/BTT-SKR-Mini-E3-V3-Firmware-CR10-Smart#2]
First, thank you so much for working on this! If I had known when I started doing the exact same project that someone else would come out with a commercial version, I would have just waited! However, I dove into this myself and made my own adapter board but am still ordering yours as a better-documented solution.

Just a quick note regarding the Z endstop. I noticed in your documentation that you don't hook up the original Z endstop and use the probe instead. I found a pretty easy solution that works to re-enable the stock Z endstop:

Connect the original 3-pin connector for the Z endstop (with the wire with the Z sleeve on it on pin 5) to pins 5, 4, and 3 of connector P3 of the BTT Skr Mini (also marked TFT on the pinout sheet, pins +5V, GND, and TX2 - which is PA2 on the microcontroller) and set PA2 to have a pull-up resistor and active low, then it works perfectly.

However, since you use the TFT pins for the display in your setup, any 5V/GND/SIG pin combination would work as long as the pin is configured with a pull-up resistor and active low. Hope this helps!

**Comment by embracemaking** [comment]
Thank you for your message and for your order, it is really appreciated. Just to clarify with your question / comment, when you say you are hooking up the original end stop, are you using it instead of the probe? So no ABL sensor?

**Comment by maximus5684** [comment]
I currently don't have the strain gague probe hooked up because I did the reverse-engineering myself and wasn't sure about the pinout. I am using the Z endstop until I get my CR-touch later today. However, it could also be used as an alternative to the virtual z endstop that is created by the probe and is much less likely to result in a crash since it is so much further above the bed surface and is more reliable than the probe. Just thought I would hand out this information since it didn't seem to be included in your product. Looking forward to receiving my boards! Also, if you want to send them unassembled, I would be happy to put them together myself to save time!

**Comment by maximus5684** [comment]
I'm actually not sure why they even include a Z endstop on this printer since it can use the strain gauge probe as a virtual one. Oh well.
